# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy an ARM template'
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Free Trial(3fa33b08-9f1e-476b-869a-2b3617d68031)'
    subscriptionId: '3fa33b08-9f1e-476b-869a-2b3617d68031'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/bigb123/azure-functions/master/functions-arm-subscription_level.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/bigb123/azure-functions/master/functions-arm-subscription_level.parameters.json'
    deploymentMode: 'Incremental'